name: Repo Sync

on:
  schedule:
  - cron:  "0 4/12 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Master Branch
        uses: tgymnich/fork-sync@v2
        with:
          owner: DIY-T1D
          base: master
          head: master
          token: ${{ secrets.GH_PAT }}

      - name: Sync Dev Branch
        uses: tgymnich/fork-sync@v2
        with:
          owner: DIY-T1D
          base: dev
          head: dev
          token: ${{ secrets.GH_PAT }}
